---
version: "3.3"
services:
  web:
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./ui-service:/var/www/html/
    depends_on:
      - db
    ports:
      - 8008:80
  db:
    container_name: mysqli
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/cms_db.sql:/docker-entrypoint-initdb.d/cms_db.sql
      - persistent:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ranjit
      MYSQL_DATABASE: ranjit
      MYSQL_USER: ranjit
      MYSQL_PASSWORD: ranjit
    ports:
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 82:80
    environment:
      MYSQL_USER: ranjit
      MYSQL_PASSWORD: ranjit
      MYSQL_ROOT_PASSWORD: ranjit
volumes:
  persistent: null