---
version: "2"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./ui-service:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: 12345
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
volumes:
    persistent: